defmodule Atlas.Repo.Migrations.AddMonitoring do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:monitoring_metric_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :metric_name, :text, null: false
      add :value, :float, null: false
      add :unit, :text
      add :tags, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :machine_id,
          references(:infrastructure_machines,
            column: :id,
            name: "monitoring_metric_snapshots_machine_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :credential_id,
          references(:credentials,
            column: :id,
            name: "monitoring_metric_snapshots_credential_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:monitoring_health_checks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :response_time_ms, :bigint
      add :details, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :machine_id,
          references(:infrastructure_machines,
            column: :id,
            name: "monitoring_health_checks_machine_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :credential_id,
          references(:credentials,
            column: :id,
            name: "monitoring_health_checks_credential_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:monitoring_alerts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :severity, :text, null: false
      add :status, :text, null: false, default: "firing"
      add :title, :text, null: false
      add :message, :text
      add :metric_name, :text
      add :threshold_value, :float
      add :actual_value, :float
      add :acknowledged_at, :utc_datetime
      add :resolved_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :machine_id,
          references(:infrastructure_machines,
            column: :id,
            name: "monitoring_alerts_machine_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :credential_id,
          references(:credentials,
            column: :id,
            name: "monitoring_alerts_credential_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:monitoring_alerts, "monitoring_alerts_machine_id_fkey")

    drop constraint(:monitoring_alerts, "monitoring_alerts_credential_id_fkey")

    drop table(:monitoring_alerts)

    drop constraint(:monitoring_health_checks, "monitoring_health_checks_machine_id_fkey")

    drop constraint(:monitoring_health_checks, "monitoring_health_checks_credential_id_fkey")

    drop table(:monitoring_health_checks)

    drop constraint(:monitoring_metric_snapshots, "monitoring_metric_snapshots_machine_id_fkey")

    drop constraint(
           :monitoring_metric_snapshots,
           "monitoring_metric_snapshots_credential_id_fkey"
         )

    drop table(:monitoring_metric_snapshots)
  end
end
