defmodule Atlas.Repo.Migrations.AddStorageBuckets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:infrastructure_storage_buckets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_id, :text, null: false
      add :name, :text, null: false
      add :size_bytes, :bigint
      add :object_count, :bigint
      add :region, :text
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :credential_id,
          references(:credentials,
            column: :id,
            name: "infrastructure_storage_buckets_credential_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:infrastructure_storage_buckets, [:provider_id, :credential_id],
             name: "infrastructure_storage_buckets_provider_credential_index"
           )
  end

  def down do
    drop_if_exists unique_index(:infrastructure_storage_buckets, [:provider_id, :credential_id],
                     name: "infrastructure_storage_buckets_provider_credential_index"
                   )

    drop constraint(
           :infrastructure_storage_buckets,
           "infrastructure_storage_buckets_credential_id_fkey"
         )

    drop table(:infrastructure_storage_buckets)
  end
end
