defmodule Atlas.Repo.Migrations.AddProvidersAndInfrastructure do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:infrastructure_volumes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_id, :text, null: false
      add :name, :text, null: false
      add :size_gb, :bigint
      add :region, :text
      add :status, :text, default: "created"
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :app_id, :uuid, null: false
      add :credential_id, :uuid, null: false
    end

    create table(:infrastructure_machines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_id, :text, null: false
      add :name, :text
      add :region, :text
      add :image, :text
      add :ip_addresses, {:array, :text}, default: []
      add :cpu_kind, :text
      add :cpus, :bigint
      add :memory_mb, :bigint
      add :gpu_type, :text
      add :status, :text, null: false, default: "created"
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :app_id, :uuid, null: false
      add :credential_id, :uuid, null: false
      add :state, :text, null: false, default: "created"
    end

    create table(:infrastructure_apps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:infrastructure_volumes) do
      modify :app_id,
             references(:infrastructure_apps,
               column: :id,
               name: "infrastructure_volumes_app_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:infrastructure_machines) do
      modify :app_id,
             references(:infrastructure_apps,
               column: :id,
               name: "infrastructure_machines_app_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:infrastructure_apps) do
      add :provider_id, :text, null: false
      add :name, :text, null: false
      add :region, :text
      add :metadata, :map, default: %{}
      add :provider_type, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :credential_id, :uuid, null: false
      add :state, :text, null: false, default: "pending"
    end

    create table(:credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:infrastructure_volumes) do
      modify :credential_id,
             references(:credentials,
               column: :id,
               name: "infrastructure_volumes_credential_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:infrastructure_volumes, [:provider_id, :credential_id],
             name: "infrastructure_volumes_provider_credential_index"
           )

    alter table(:infrastructure_machines) do
      modify :credential_id,
             references(:credentials,
               column: :id,
               name: "infrastructure_machines_credential_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:infrastructure_machines, [:provider_id, :credential_id],
             name: "infrastructure_machines_provider_credential_index"
           )

    alter table(:infrastructure_apps) do
      modify :credential_id,
             references(:credentials,
               column: :id,
               name: "infrastructure_apps_credential_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:infrastructure_apps, [:provider_id, :credential_id],
             name: "infrastructure_apps_provider_credential_index"
           )

    alter table(:credentials) do
      add :provider_type, :text, null: false
      add :name, :text, null: false
      add :org_slug, :text
      add :sync_enabled, :boolean, null: false, default: true
      add :sync_interval_seconds, :bigint, null: false, default: 60
      add :last_synced_at, :utc_datetime
      add :status, :text, null: false, default: "active"
      add :status_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_api_token, :binary, null: false
    end
  end

  def down do
    alter table(:credentials) do
      remove :encrypted_api_token
      remove :updated_at
      remove :inserted_at
      remove :status_message
      remove :status
      remove :last_synced_at
      remove :sync_interval_seconds
      remove :sync_enabled
      remove :org_slug
      remove :name
      remove :provider_type
    end

    drop_if_exists unique_index(:infrastructure_apps, [:provider_id, :credential_id],
                     name: "infrastructure_apps_provider_credential_index"
                   )

    drop constraint(:infrastructure_apps, "infrastructure_apps_credential_id_fkey")

    alter table(:infrastructure_apps) do
      modify :credential_id, :uuid
    end

    drop_if_exists unique_index(:infrastructure_machines, [:provider_id, :credential_id],
                     name: "infrastructure_machines_provider_credential_index"
                   )

    drop constraint(:infrastructure_machines, "infrastructure_machines_credential_id_fkey")

    alter table(:infrastructure_machines) do
      modify :credential_id, :uuid
    end

    drop_if_exists unique_index(:infrastructure_volumes, [:provider_id, :credential_id],
                     name: "infrastructure_volumes_provider_credential_index"
                   )

    drop constraint(:infrastructure_volumes, "infrastructure_volumes_credential_id_fkey")

    alter table(:infrastructure_volumes) do
      modify :credential_id, :uuid
    end

    drop table(:credentials)

    alter table(:infrastructure_apps) do
      remove :state
      remove :credential_id
      remove :updated_at
      remove :inserted_at
      remove :synced_at
      remove :status
      remove :provider_type
      remove :metadata
      remove :region
      remove :name
      remove :provider_id
    end

    drop constraint(:infrastructure_machines, "infrastructure_machines_app_id_fkey")

    alter table(:infrastructure_machines) do
      modify :app_id, :uuid
    end

    drop constraint(:infrastructure_volumes, "infrastructure_volumes_app_id_fkey")

    alter table(:infrastructure_volumes) do
      modify :app_id, :uuid
    end

    drop table(:infrastructure_apps)

    drop table(:infrastructure_machines)

    drop table(:infrastructure_volumes)
  end
end
